# Generated by Django 6.0.3 on 2026-07-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Furniture',
        ),
    ]
